to s3
frictionlessdata/datapackage-pipelines-aws pull request #2
Opened 2017-07-05 21:14 UTC by zelima

This pull request fixes #1 

* [x] I've added tests to cover the proposed changes
  * partially - see note

Changes proposed in this pull request:

- helper function to format path (Key) to the file on s3
- a processor for putting files on s3
- deps updated for test

@akariv Note:

The PR is not complete - the tests are not checking if resources are on s3 as well, cause I could not find an easy way to pass the resource iterator to `mock_processor_test`. Some help would be useful

2017-07-06 09:10 UTC, akariv requested changes

2017-07-06 09:10 UTC, akariv commented on datapackage_pipelines_aws/helpers.py
> +    vers = datapackage.get('version', 'latest')
This feels a bit hard-coded to me.

We could use a simpler (and more powerful):
`path = base_path.format(**self.datapackage)`
no?

2017-07-06 09:10 UTC, akariv commented on datapackage_pipelines_aws/processors/to_s3.py
> +        self.bucket = params['bucket']
What about AWS access key and secret?

2017-07-06 09:10 UTC, akariv commented on datapackage_pipelines_aws/helpers.py
> +    vers = datapackage.get('version', 'latest')
or even:
```python
format_params = {'version': 'latest'}
format_params.update(self.datapackage)
base_path.format(**format_params)
```

2017-07-06 09:10 UTC, akariv commented on tests/test_to_s3.py
> +                            iter([])))
This should be a list of lists of the resource data. e.g.:

[ 
  [ {'Name': 'a', 'Date': datetime.datetime.now().date()}, ... 
  ] 
]

2017-07-06 12:06 UTC, zelima commented on datapackage_pipelines_aws/processors/to_s3.py
> +        self.bucket = params['bucket']
@akariv boto3 takes care of credential if they are set-up. It looks up in aws config file or searches for ENV variables http://boto3.readthedocs.io/en/latest/guide/configuration.html#aws-config-file
But we can have them as a part of the spec as well if that is a case

2017-07-06 12:10 UTC, zelima commented on tests/test_to_s3.py
> +                            iter([])))
I'm getting this error in that case 
```
def handle_resources(self, datapackage,
                         resource_iterator,
                         parameters, stats):
        datapackage['count_of_rows'] = 0
        datapackage['hash'] = hashlib.md5()
        for resource in resource_iterator:
>           resource_spec = resource.spec
E           AttributeError: 'list' object has no attribute 'spec'
```

2017-07-06 17:06 UTC, akariv commented on tests/test_to_s3.py
> +                            iter([])))
Okay, try this:
```
res =  [ {'Name': 'a', 'Date': datetime.datetime.now().date()}, ... ] 
res.spec = datapackage['resources'][0]
res_iter = [res]
```

We should probably find a wrapper for that.

2017-07-06 18:26 UTC, akariv commented on tox.ini
> +	google-compute-engine
google-compute-engine?

2017-07-06 19:10 UTC, zelima commented on tox.ini
> +	google-compute-engine
boto was complaining on Travis 
```
Traceback:
tests/test_to_s3.py:5: in <module>
    from moto import mock_s3
.tox/py/lib/python3.6/site-packages/moto/__init__.py:9: in <module>
    from .autoscaling import mock_autoscaling, mock_autoscaling_deprecated  # flake8: noqa
.tox/py/lib/python3.6/site-packages/moto/autoscaling/__init__.py:2: in <module>
    from .models import autoscaling_backends
.tox/py/lib/python3.6/site-packages/moto/autoscaling/models.py:2: in <module>
    from boto.ec2.blockdevicemapping import BlockDeviceType, BlockDeviceMapping
.tox/py/lib/python3.6/site-packages/boto/__init__.py:1216: in <module>
    boto.plugin.load_plugins(config)
.tox/py/lib/python3.6/site-packages/boto/plugin.py:93: in load_plugins
    _import_module(file)
.tox/py/lib/python3.6/site-packages/boto/plugin.py:75: in _import_module
    return imp.load_module(name, file, filename, data)
.tox/py/lib/python3.6/imp.py:234: in load_module
    return load_source(name, filename, file)
.tox/py/lib/python3.6/imp.py:172: in load_source
    module = _load(spec)
/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py:19: in <module>
    from google_compute_engine import logger
E   ModuleNotFoundError: No module named 'google_compute_engine'
```
This answer summarises the reason https://github.com/GoogleCloudPlatform/compute-image-packages/issues/262#issuecomment-225736860

2017-07-10 08:04 UTC, akariv approved these changes

2017-07-10 08:05 UTC, merged